version: '3'
services:
    web:
      build:
        context: .
        dockerfile: Dockerfile  
      # volumes:
      #  - app:./build/
      # command: npm start
      # ports:
      #   - '3000:3000'
    # nginx:
    #   build:
    #    context: ./nginx
    #    dockerfile: Dockerfile
      ports:
        - "80:80"
      # volumes:
      #   - website:/usr/share/nginx/html/website # Copy React App's build files to the Nginx directory

    # volumes:
    #   website: