name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Login to Docker Hub 
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t cliu232/networking-platform-cicd .
      - name: Publish image to docker hub
        run: docker push cliu232/networking-platform-cicd
  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull image from docker hub
        run: docker pull cliu232/networking-platform-cicd
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer cliu232/networking-platform-cicd
